spring.application.name=jpa

spring.datasource.url=jdbc:mysql://localhost:3306/hospitalDB?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin

#spring.datasource.2nd.url=jdbc:mysql://localhost:3306/jpa_tutorial?useSSL=false
#spring.datasource.2nd.username=root
#spring.datasource.2nd.password=admin

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#Config to create data using data.sql manuall
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql